#!/usr/bin/env bash

case "$1" in
  -m)
    php modules/.tracem.php
  ;;
  -t)
    case "$#" in
    2)
      php modules/.traceip.php $2
    ;;
    *)
      echo "error : invalid arguments !!"
      echo "use: ip-tracer -t <target_ip>"
    ;;
    esac
  ;;
  -u)
    php modules/.update.php
    exit
  ;;
  update)
    php modules/.update.php
    exit
  ;;
  start)
    php .IP-Tracer.php
    exit
  ;;
  -rm)
    php modules/.uninstall.php
    exit
  ;;
  *)
    echo "Usage: ip-tracer [command]... [arguments]..."
    echo " Commands:"
    echo " -t <target_ip>      para rastrear o ip de destino."
    echo " -m                 para rastrear seu próprio ip."
    echo " -h                  para mostrar ajuda."
    echo " -u                  para atualizar o ip-tracer."
    echo " help                para mostrar ajuda."
    echo " update              para atualizar o ip-tracer."
    echo " start               para iniciar o menu ip-tracer."
esac
